spring.application.name=screenmatch

spring.datasource.url=${url}
spring.datasource.hikari.schema=screenmatch
spring.datasource.username=${user_db}
spring.datasource.password=${password_db}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true